name: CI - Mission Safety Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Code quality check job
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        
      # Set up JDK for Java
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Run Checkstyle (Java code quality)
      - name: Run Checkstyle
        run: ./mvnw checkstyle:check # This assumes you have Checkstyle configured in your `pom.xml`
        
  # Unit test job
  test:
    runs-on: ubuntu-latest
    needs: lint  # This job depends on lint
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        
      # Set up JDK for Java
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Install dependencies using Maven
      - name: Install dependencies
        run: ./mvnw clean install # This will install dependencies and compile the project

      # Run unit tests with Maven
      - name: Run unit tests (JUnit)
        run: ./mvnw test # Runs the unit tests with Maven (you can adjust based on your testing framework)

  # Build job 
  build:
    runs-on: ubuntu-latest
    needs: test  # This job depends on tests
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        
      # Set up JDK for Java
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build the Spring Boot application
      - name: Build application
        run: ./mvnw package -DskipTests # Skips tests during the build step; adjust if necessary

  # Deploy job
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build  # This job depends on build
  #   steps:
  #     - name: Check out the repository
  #       uses: actions/checkout@v2
        
  #     # Set up JDK for Java
  #     - name: Set up JDK 17
  #       uses: actions/setup-java@v2
  #       with:
  #         java-version: '17'
  #         distribution: 'temurin'

  #     # Deploy the application (adjust based on your deployment process)
  #     - name: Deploy application
  #       run: |
  #         echo "Deploying application..."
  #         # Add your deployment steps here

