name: Build and Push Docker Image

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest  # You can use other environments too, like 'windows-latest'

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Log in to Docker Hub (using GitHub secrets for Docker credentials)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd_assign:latest .

    # Step 5: Push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        context: .
        docker push ${{ secrets.DOCKER_USERNAME }}/cicd_assing_repo/cicd_assign:latest

